# Generated by Django 5.1.7 on 2025-03-18 05:33

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
